export const COLLECTIONS = {
  EVENT_BANNER: 'EVENT_BANNER',
  CARD: 'CARD',
  EVENT: 'EVENT',
  CREDIT: 'CREDIT',
  TERMS: 'TERMS',
  ACCOUNT: 'ACCOUNT',
  TRANSACTION: 'TRANSACTION',
  PIGGYBANK: 'PIGGYBANK',
  FAQ: 'FAQ',
}
